### ISSUE TITLE
Is it possible to use React in front-end

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/metalsmith-react#4]
Hi,
I'm in the progress of tranforming my personal blog from Jekyll to Metalsmith. Since I'm doing most of my day job with React. It would be great to build my blog with React too. And I found your project which is pretty awesome. 

I wonder if it is possible to use React in front-end for dynamic stuff like: Sidebar toggle, animation, ....

**Comment by MoOx** [comment]
I don't use metalsmith anymore and that's a reeaaaally good question.
This can be probably done, but I think using metalsmith for this is not the right choice.

That's why I created a specific engine and I am actively working on it.
I will be very happy that you try it and will provide support via issue or chat since the project need some new users.

http://moox.io/statinamic/
https://github.com/MoOx/statinamic

**Comment by MoOx** [comment]
Note: I plan to release a new version with a better default boilerplate tonight or tomorrow.

**Comment by thangngoc89** [comment]
@MoOx Great. I'll look in to it.

**Comment by cameronjroe** [comment]
Hi guys, I'm also looking for a similar solution. I started playing around [here](https://github.com/cameronjroe/kosmos). Would love to help get one of these projects off the ground.

**Comment by thangngoc89** [comment]
@cameronjoe I joined the force with @MoOx .  statinamic is at a good state now

**Comment by MoOx** [comment]
@cameronjroe you really should take a look to https://github.com/MoOx/statinamic. Hours have been spent to reach the current state of this project, it's mature enough to use it for a blog (or more).

**Comment by cameronjroe** [comment]
Awesome! I'm really frustrated with templating in metalsmith. I'm testing statinamic now. Thanks for creating it!
